In [1]:
import numpy as np
from colorama import Fore

In [13]:
# I all you know how to create the array if you missed check this out.
# https://github.com/harikrishna7696/Datascience_Ml_Revision/blob/main/Numpy/Numpy_Basic.ipynb
# I created a python list
li = [i for i in range(1, 10)]
print(Fore.GREEN, "list: ", li)


# we have a len(iterable) function in python, we can find length

print(Fore.RED, "Length of the list: ", len(li))
print(" We have a 9 values in the list.")

 list:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
 Length of the list:  9
 We have a 9 values in the list.


## How do you know the shape and size of an array?

In [102]:
# we can convert the list into array
arr = np.array(li)
print(Fore.GREEN, "array: ",arr)

# same like len in array we have arr.size, it will return the length
print(Fore.GREEN, "Length of the array: ", arr.size)

print(Fore.RED, "You can observe the length of the arr and list are same 9.")

 array:  [1 2 3 4 5 6 7 8 9]
 Length of the array:  9
 You can observe the length of the arr and list are same 9.


## np.argmax()

In [103]:
# using this you can print the maximum number index
print("argmax: ", np.argmax(arr))

argmax:  8


In [33]:
## some other usefull function to know about array shape and lenght
print(Fore.RED, "Using arr.ndim, we get to know how many dimensions.")
print(Fore.GREEN, "Array dimension", arr.ndim)

## arr.shape, it return the shape how many rown and columns
arr1 = np.ones((2, 4))
print(" arr1: ", arr1)
print(Fore.RED, "I created a array with 2 rows and 4 columns, let's check the shape.")
print(Fore.GREEN, "arr1 shape: ", arr1.shape)

 Using arr.ndim, we get to know how many dimensions.
 Array dimension 1
 arr1:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 I created a array with 2 rows and 4 columns, let's check the shape.
 arr1 shape:  (2, 4)


## Adding, removing, and sorting elements

## Addition

In [64]:
arr2 = np.array([[5,8,9,4],[8,4,9,49]])
arr3 = np.array([[9,8,7,5],[7,9,6,9]])

## np.addition()

In [51]:
## If you want to do the addition between to arrays.
## array must be same shape.
## np.add(arr1, arr2)
arr5 = np.add(arr2, arr3)
print(Fore.GREEN, "Adding arrays: ", arr5)

# also you can use arr1 + arr2
print(Fore.GREEN, "arr2 + arr3: ", arr2 + arr3)

 Adding arrays:  [[14 16 16  9]
 [15 13 15 58]]
 arr2 + arr3:  [[14 16 16  9]
 [15 13 15 58]]


## Multiplication

## np.multiply()

In [58]:
# Multiplying two arrays.
arr6 = np.multiply(arr2, arr3)
print(Fore.GREEN, "Multiply arrays: ", arr5)

# also you can use arr1 * arr2.
print(Fore.GREEN, "arr2 * arr3: ", arr2 * arr3)

 Multiply arrays:  [[14 16 16  9]
 [15 13 15 58]]
 arr2 * arr3:  [[ 45  64  63  20]
 [ 56  36  54 441]]


## Subtraction

## np.subtract()

In [59]:
# Subtracting two arrays
arr7= np.subtract(arr2, arr3)
print(Fore.GREEN, "Subtraction arrays: ", arr5)

# also you can use arr1 - arr2
print(Fore.GREEN, "arr2 - arr3: ", arr2 + arr3)

 Subtraction arrays:  [[14 16 16  9]
 [15 13 15 58]]
 arr2 - arr3:  [[14 16 16  9]
 [15 13 15 58]]


## Division

## np.divide()

In [61]:
# Division two arrays
arr8= np.divide(arr2, arr3)
print(Fore.GREEN, "Subtraction arrays: ", arr8)

# also you can use arr1 % arr2
print(Fore.GREEN, "arr2 % arr3: ", arr2 + arr3)

 Subtraction arrays:  [[0.55555556 1.         1.28571429 0.8       ]
 [1.14285714 0.44444444 1.5        5.44444444]]
 arr2 % arr3:  [[14 16 16  9]
 [15 13 15 58]]


## Note: For mathematical operations numpy is very faster than list.

In [70]:
# concatenating 2 arrays in one array.

print(Fore.GREEN, "arr2 shape: ", arr2.shape)
print(Fore.GREEN, "arr3 shape: ", arr3.shape)

# np.concatenate((arr1, arrr2, ..), axis=0, out=None, dtype=None)
# The arrays must have the same shape, except in the dimension corresponding to axis.
arr4 = np.concatenate((arr2, arr3))
print(" arr4: ", arr4)
print(" arr4 shape: ", arr4.shape)

# np.stack(arrays, axis, ..), it will stack the array.
# Join a sequence of arrays along a new axis.
arr8 = np.stack((arr2, arr3))
print("\nnp.stack arr8: ", arr8)
print("arr8 shape: ", arr8.shape)

 arr2 shape:  (2, 4)
 arr3 shape:  (2, 4)
 arr4:  [[ 5  8  9  4]
 [ 8  4  9 49]
 [ 9  8  7  5]
 [ 7  9  6  9]]
 arr4 shape:  (4, 4)

np.stack arr8:  [[[ 5  8  9  4]
  [ 8  4  9 49]]

 [[ 9  8  7  5]
  [ 7  9  6  9]]]
arr8 shape:  (2, 2, 4)


## Sorting

## np.sort()

In [78]:
# creating array with random numbers.
arr9 = np.random.randint(2, 100, 20)
print(Fore.RED, "Array with random numbers: ", arr9)

# np.sort() -> It will return as sorted array.
# Note: It doesn't sort in original array.
arr10 = np.sort(arr9)
print(Fore.GREEN, "Sorted array: ", arr10)
# If you print the arr9, It will be in random numbers only. let's check for your better clarification.
print(" Arr9:", arr9)

 Array with random numbers:  [71  4 92 89 40 48 56 92 31 59 50 38 22  3 44 45 99 95 48 84]
 Sorted array:  [ 3  4 22 31 38 40 44 45 48 48 50 56 59 71 84 89 92 92 95 99]
 Arr9: [71  4 92 89 40 48 56 92 31 59 50 38 22  3 44 45 99 95 48 84]


## np.argsort()

In [91]:
# this will return the array of sorted indices.
# Note: It doesn't sort array with values, it sort values and return indexes

arr11 = np.argsort(arr9)
print(Fore.GREEN, "Array with Random numbers: ", arr9)
print(Fore.GREEN, "Indexes of sorted array: ", arr11)

 Array with Random numbers:  [71  4 92 89 40 48 56 92 31 59 50 38 22  3 44 45 99 95 48 84]
 Indexes of sorted array:  [13  1 12  8 11  4 14 15  5 18 10  6  9  0 19  3  2  7 17 16]


## Note: We have some other sort function, but for basics it will be ok. Remaining I will post in Advance array operations