In [3]:
# creating a list and let's convert into array using the different functions
import numpy as np

l = [1,2,3,4]
arr = np.array(l)
arr

array([1, 2, 3, 4])

In [5]:
# mat -> It also an array
# matrix is multi dimensional array
np.mat(l)

matrix([[1, 2, 3, 4]])

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [8]:
arr = np.array([[1,2,3,4], [7,8,9,10]])
arr

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [9]:
# lets make copy of array and assign to varible

a = arr
a

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [11]:
b = arr.copy()
b

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [12]:
# let change the value of arr[0][1] -> 7696

arr[0][1] = 7696
arr

array([[   1, 7696,    3,    4],
       [   7,    8,    9,   10]])

In [14]:
# if you pring the a 
a
# if you observe the value is changed
# you know the assignment of value to varible
# In pythone if you assigning some value as copy it won't store the data, it point to that original value address
# If you change anything in original it will reflect in copy

array([[   1, 7696,    3,    4],
       [   7,    8,    9,   10]])

In [16]:
# The best way to is use iteratable.copy()
b
# Here change is not occured becaue it copy that value and store different address
# Changing in the original value, it won't effect the copied value

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [18]:
# another way to copy array is np.copy
c = np.copy(b)
c

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [20]:
# you can also use loops to get the values
for i in c:
    print(i)

[1 2 3 4]
[ 7  8  9 10]


In [24]:
# it is type of array creation, it will create the array with given condition function
# np.fromfunction(func, shape, dtype=defualt(float))
np.fromfunction(lambda i, j: i//2==0, (5, 5))

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [25]:
np.fromfunction(lambda i, j: i+j*2, (4, 4))

array([[0., 2., 4., 6.],
       [1., 3., 5., 7.],
       [2., 4., 6., 8.],
       [3., 5., 7., 9.]])

In [33]:
np.fromfunction(lambda i, j:np.square(i+j), (5, 5))

array([[ 0.,  1.,  4.,  9., 16.],
       [ 1.,  4.,  9., 16., 25.],
       [ 4.,  9., 16., 25., 36.],
       [ 9., 16., 25., 36., 49.],
       [16., 25., 36., 49., 64.]])

In [40]:
# creating the array using the iterator

generator = (i for i in range(10))
generator

<generator object <genexpr> at 0x000001E06BB22A40>

In [41]:
# generator is nothing but it creates the data
generator.__next__()

0

In [42]:
# __next__() with generator object it returns the data
# here we got from 1 because we already got 0 from __next__() function, once it return the value it forget
# np.fromiter(generator, dtype=float) dtype is required
np.fromiter(generator, dtype=float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
# if you run again with that generator.
# it will return the empty, because we already extraced the values above
# Note: I previously mentioned once we access the values it will forget, 
# and keep in my mind, we cannot access with index and also we can't do slicing
np.fromiter(generator, dtype=float)

array([], dtype=float64)

In [50]:
# ex: lets create generator with 10
gen = (i for i in range(10))
gen

<generator object <genexpr> at 0x000001E06BF98270>

In [51]:
for i in range(0, 10):
    print(gen.__next__())

0
1
2
3
4
5
6
7
8
9


In [54]:
# This will be very intersting, you know you can create array with string
# fromstring(str, sep='', dtype=int)
np.fromstring('10, 20, 30, 40, 50, 60', sep=',', dtype=int)

array([10, 20, 30, 40, 50, 60])

In [55]:
np.fromstring('50-60-80-90-100', sep='-')

array([ 50.,  60.,  80.,  90., 100.])

In [73]:
# let's jump into multi dimensional array

arr2 = np.array([[[1,2,3,6,4], [4,5,8,1,2]], [[1,2,3,6,4], [4,5,8,1,2]]])
arr2

array([[[1, 2, 3, 6, 4],
        [4, 5, 8, 1, 2]],

       [[1, 2, 3, 6, 4],
        [4, 5, 8, 1, 2]]])

In [74]:
arr2.size # we have 20 values

20

In [75]:
arr2.ndim # It is 4 dimensional arrat

3

In [77]:
arr2.shape # we have 2 rows which contains (2, 4) shape 2rows 4 columns

(2, 2, 5)

In [79]:
# In python list using range(int), you can only give int, it wont take float
range(6.6)

TypeError: 'float' object cannot be interpreted as an integer

In [80]:
# but in numpy array using arange() you can give floating numbers
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [82]:
np.arange(1, 6, 1.5)

array([1. , 2.5, 4. , 5.5])

In [84]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [86]:
# if you give negative index for incremented array it will return empty array, it won't throw error
np.arange(4, 5, -1)

array([], dtype=int32)

In [94]:
# Similar to logspace, but with the samples uniformly distributed in linear space, instead of log space.
np.logspace(1, 10, endpoint=True, axis=0)

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

In [96]:
np.logspace([20, 40], 10, endpoint=True, axis=1)

array([[1.00000000e+20, 6.25055193e+19, 3.90693994e+19, 2.44205309e+19,
        1.52641797e+19, 9.54095476e+18, 5.96362332e+18, 3.72759372e+18,
        2.32995181e+18, 1.45634848e+18, 9.10298178e+17, 5.68986603e+17,
        3.55648031e+17, 2.22299648e+17, 1.38949549e+17, 8.68511374e+16,
        5.42867544e+16, 3.39322177e+16, 2.12095089e+16, 1.32571137e+16,
        8.28642773e+15, 5.17947468e+15, 3.23745754e+15, 2.02358965e+15,
        1.26485522e+15, 7.90604321e+14, 4.94171336e+14, 3.08884360e+14,
        1.93069773e+14, 1.20679264e+14, 7.54312006e+13, 4.71486636e+13,
        2.94705170e+13, 1.84206997e+13, 1.15139540e+13, 7.19685673e+12,
        4.49843267e+12, 2.81176870e+12, 1.75751062e+12, 1.09854114e+12,
        6.86648845e+11, 4.29193426e+11, 2.68269580e+11, 1.67683294e+11,
        1.04811313e+11, 6.55128557e+10, 4.09491506e+10, 2.55954792e+10,
        1.59985872e+10, 1.00000000e+10],
       [1.00000000e+40, 2.44205309e+39, 5.96362332e+38, 1.45634848e+38,
        3.55648031e+37,

In [99]:
# we can also create the array with random numbers
np.random.randn(4) # it will return the array with 4 random values

array([ 0.49410145,  1.06278933, -0.03329742,  0.35482207])

In [101]:
#np.random.randint(start, stop, size=(row, column))
np.random.randint(2, 100, (10, 5)) 

array([[59, 55, 22, 18,  4],
       [70, 98, 13, 33, 84],
       [92, 60, 58, 38, 16],
       [98, 83, 49, 17, 76],
       [41, 85, 72, 60, 27],
       [97, 24, 37, 92, 69],
       [60, 48,  3, 29, 96],
       [37, 47, 48,  5,  6],
       [ 4, 99, 62, 20, 62],
       [ 2, 19, 88, 72, 59]])

In [105]:
# using random_sample you create the, 
# giving the shape as input it will return array with some random sample
arr = np.random.random_sample((5, 10))
arr

array([[0.32835842, 0.6192776 , 0.40058841, 0.57889582, 0.62058741,
        0.90903836, 0.7539173 , 0.0846393 , 0.84325526, 0.35064235],
       [0.40530894, 0.09145781, 0.92053969, 0.18269584, 0.02312549,
        0.72773282, 0.37334738, 0.38432538, 0.26789167, 0.20662599],
       [0.73674017, 0.12190745, 0.42050156, 0.2229833 , 0.42238046,
        0.88748881, 0.2145482 , 0.70017495, 0.96352267, 0.95614605],
       [0.15561046, 0.60857519, 0.6866634 , 0.11539209, 0.95383428,
        0.27060933, 0.17693925, 0.11082144, 0.59864473, 0.87580489],
       [0.28902129, 0.13385403, 0.43725623, 0.73943865, 0.17817223,
        0.69763972, 0.76340672, 0.60086517, 0.12248608, 0.47047758]])

In [108]:
arr[0:5, [1, 2, 3]]

array([[0.6192776 , 0.40058841, 0.57889582],
       [0.09145781, 0.92053969, 0.18269584],
       [0.12190745, 0.42050156, 0.2229833 ],
       [0.60857519, 0.6866634 , 0.11539209],
       [0.13385403, 0.43725623, 0.73943865]])

In [110]:
arr[:, 4:6]

array([[0.62058741, 0.90903836],
       [0.02312549, 0.72773282],
       [0.42238046, 0.88748881],
       [0.95383428, 0.27060933],
       [0.17817223, 0.69763972]])

In [112]:
arr[:, [0, 3]]

array([[0.32835842, 0.57889582],
       [0.40530894, 0.18269584],
       [0.73674017, 0.2229833 ],
       [0.15561046, 0.11539209],
       [0.28902129, 0.73943865]])