In [5]:
import numpy as np
# lets create  2 arrays and let perform few mathematical operations
arr1 = np.arange(5, 10)
arr2 = np.arange(15, 20)
print(arr1.shape)
print(arr2.shape)

(5,)
(5,)


In [6]:
# Adding 2 arrays
print(arr1 + arr2)
# addition of 2 arrays

[20 22 24 26 28]


In [8]:
# if you give 2 different shapes, it will throw error "ValueError: operands could not be broadcast together with shapes"
arr3 = np.array([1, 2, 45])
arr4 = np.array([2, 1])
print(arr3 + arr4)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [16]:
# The array must be match interms of row or columns
# ex: (2,4) (2, 1)

arr5 = np.array([[2, 1, 5, 6], [5,9,7,8]])
arr6 = np.array([[4], [5]])
print(arr5.shape, arr6.shape)
print(arr5+arr6)

(2, 4) (2, 1)
[[ 6  5  9 10]
 [10 14 12 13]]


In [17]:
# ex: (2,4) (1, 4)

arr5 = np.array([[2, 1, 5, 6], [5,9,7,8]])
arr6 = np.array([[4, 5, 8,5]])
print(arr5.shape, arr6.shape)
print(arr5+arr6)

(2, 4) (1, 4)
[[ 6  6 13 11]
 [ 9 14 15 13]]
